apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  USERNAME: my-username

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  API_KEY: bXktYXBpLWtleQ==  # "my-api-key" en base64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: web-app-container
        image: localhost:8081/tarea5/nexus:latest
        env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USERNAME
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: API_KEY
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
